# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
#image: registry.gitlab.com/pages/hugo_extended:latest
image:
  name: peaceiris/hugo:v0.82.0
  entrypoint: [""]

pages:
  script:
  - hugo --minify
  artifacts:
    paths:
    - public
  only:
  - master

